In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('./911-all - 911.csv')

In [31]:
df.head()

,X.periodo,escuela,cve.municipio,municipio,programa,programa.desglose,clave.carr,carrera,nuevo.ingreso,egresados,titulados,clasificacion,region,matricula
0,p2014-2015,UNIVERSIDAD PEDAG√ìGICA NACIONAL 141,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,511300009,LICENCIATURA EN INTERVENCI√ìN EDUCATIVA,22,16,11,OTRO,centro,71
1,p2014-2015,UNIVERSIDAD PEDAG√ìGICA NACIONAL 141,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,511000007,LICENCIATURA EN EDUCACI√ìN,0,0,18,OTRO,centro,0
2,p2014-2015,UNIVERSIDAD PEDAG√ìGICA NACIONAL 142,98,SAN PEDRO TLAQUEPAQUE,LICENCIATURA,LICENCIATURA,511300009,LICENCIATURA EN INTERVENCI√ìN EDUCATIVA,44,43,11,OTRO,centro,209
3,p2014-2015,UNIVERSIDAD PEDAG√ìGICA NACIONAL 142,98,SAN PEDRO TLAQUEPAQUE,LICENCIATURA,LICENCIATURA,511000007,LICENCIATURA EN EDUCACI√ìN,0,0,59,OTRO,centro,44
4,p2014-2015,UNIVERSIDAD PEDAG√ìGICA NACIONAL 143,15,AUTLAN DE NAVARRO,LICENCIATURA,LICENCIATURA,511300009,LICENCIATURA EN INTERVENCI√ìN EDUCATIVA,24,19,13,OTRO,sierra.amula,76

In [32]:
# Filtrar los datos más recientes (2022-2023) usando el vector de municipios
municipios_vector = [39]  # Agrega los municipios que desees filtrar
filtered_df = df[(df['X.periodo'] >= 'p2022-2023') & (df['cve.municipio'].isin(municipios_vector))]

In [33]:
filtered_df

,X.periodo,escuela,cve.municipio,municipio,programa,programa.desglose,clave.carr,carrera,nuevo.ingreso,egresados,titulados,clasificacion,region,matricula
9964,p2022-2023,UNIVERSIDAD PEDAGOGICA NACIONAL 141,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5011100015,LICENCIATURA EN PEDAGOGÍA,65,85,19,OTRO,NaN,289
9965,p2022-2023,UNIVERSIDAD PEDAGOGICA NACIONAL 141,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5011300009,LICENCIATURA EN INTERVENCIÓN EDUCATIVA,0,1,10,OTRO,NaN,0
9966,p2022-2023,UNIVERSIDAD PEDAGOGICA NACIONAL 141,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5011500002,LICENCIATURA EN EDUCACIÓN,0,0,5,OTRO,NaN,0
10018,p2022-2023,SISTEMA DE UNIVERSIDAD VIRTUAL,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5011200004,LICENCIATURA EN DESARROLLO EDUCATIVO,98,134,73,UDG,NaN,692
10019,p2022-2023,SISTEMA DE UNIVERSIDAD VIRTUAL,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5011500002,LICENCIATURA EN EDUCACIÓN,0,14,47,UDG,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11683,p2022-2023,UNIVERSIDAD UNIVER PLANTEL AVILA CAMACHO,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5033100011,LICENCIATURA EN DERECHO,0,0,0,OTRO,NaN,11
11684,p2022-2023,UNIVERSIDAD UNIVER PLANTEL AVILA CAMACHO,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5011100015,LICENCIATURA EN PEDAGOGÍA,0,0,0,OTRO,NaN,60
11685,p2022-2023,UNIVERSIDAD UNIVER PLANTEL AVILA CAMACHO,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5033100011,LICENCIATURA EN DERECHO,0,0,0,OTRO,NaN,37
11686,p2022-2023,UNIVERSIDAD UNIVER PLANTEL JARDINES DEL COUNTRY,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5073100009,LICENCIATURA EN ARQUITECTURA,0,0,0,OTRO,NaN,10
11687,p2022-2023,UNIVERSIDAD UNIVER PLANTEL JARDINES DEL COUNTRY,39,GUADALAJARA,LICENCIATURA,LICENCIATURA,5021500028,LICENCIATURA EN DISEÑO GRÁFICO,0,0,0,OTRO,NaN,5

In [49]:
# Filtrar las carreras tecnológicas que comienzan con 54, 55, 56 y 57
carreras_tecnologicas = filtered_df[filtered_df['programa'] == 'TECNOLOGICO']

In [50]:
carreras_tecnologicas

Empty DataFrame
Columns: [X.periodo, escuela, cve.municipio, municipio, programa, programa.desglose, clave.carr, carrera, nuevo.ingreso, egresados, titulados, clasificacion, region, matricula]
Index: []

In [43]:
total_carreras_tecnologicas = carreras_tecnologicas['nuevo.ingreso'].sum() + carreras_tecnologicas['egresados'].sum() + carreras_tecnologicas['titulados'].sum()
print("Total de carreras tecnológicas (2022-2023):", total_carreras_tecnologicas)

Total de carreras tecnológicas (2022-2023): 0

In [36]:
historico_carreras_tecnologicas = df[(df['X.periodo'] >= '2014') & df['carrera'].str.startswith(('54', '55', '56', '57'))]

In [37]:
# Mostrar los resultados
print("Datos filtrados:")
print(filtered_df)

print("\nTotal de estudiantes en carreras tecnológicas (2022-2023):", total_carreras_tecnologicas)

print("\nHistórico de estudiantes desde 2014-2015:")
print(historico_carreras_tecnologicas)

Datos filtrados:
        X.periodo                                          escuela  \
9964   p2022-2023              UNIVERSIDAD PEDAGOGICA NACIONAL 141
9965   p2022-2023              UNIVERSIDAD PEDAGOGICA NACIONAL 141
9966   p2022-2023              UNIVERSIDAD PEDAGOGICA NACIONAL 141
10018  p2022-2023                   SISTEMA DE UNIVERSIDAD VIRTUAL
10019  p2022-2023                   SISTEMA DE UNIVERSIDAD VIRTUAL
...           ...                                              ...
11683  p2022-2023         UNIVERSIDAD UNIVER PLANTEL AVILA CAMACHO
11684  p2022-2023         UNIVERSIDAD UNIVER PLANTEL AVILA CAMACHO
11685  p2022-2023         UNIVERSIDAD UNIVER PLANTEL AVILA CAMACHO
11686  p2022-2023  UNIVERSIDAD UNIVER PLANTEL JARDINES DEL COUNTRY
11687  p2022-2023  UNIVERSIDAD UNIVER PLANTEL JARDINES DEL COUNTRY

       cve.municipio    municipio      programa programa.desglose  clave.carr  \
9964              39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5011100015
9965              39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5011300009
9966              39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5011500002
10018             39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5011200004
10019             39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5011500002
...              ...          ...           ...               ...         ...
11683             39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5033100011
11684             39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5011100015
11685             39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5033100011
11686             39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5073100009
11687             39  GUADALAJARA  LICENCIATURA      LICENCIATURA  5021500028

                                      carrera  nuevo.ingreso  egresados  \
9964                LICENCIATURA EN PEDAGOGÍA             65         85
9965   LICENCIATURA EN INTERVENCIÓN EDUCATIVA              0          1
9966                LICENCIATURA EN EDUCACIÓN              0          0
10018    LICENCIATURA EN DESARROLLO EDUCATIVO             98        134
10019               LICENCIATURA EN EDUCACIÓN              0         14
...                                       ...            ...        ...
11683                 LICENCIATURA EN DERECHO              0          0
11684               LICENCIATURA EN PEDAGOGÍA              0          0
11685                 LICENCIATURA EN DERECHO              0          0
11686            LICENCIATURA EN ARQUITECTURA              0          0
11687          LICENCIATURA EN DISEÑO GRÁFICO              0          0

       titulados clasificacion region matricula
9964          19          OTRO    NaN       289
9965          10          OTRO    NaN         0
9966           5          OTRO    NaN         0
10018         73           UDG    NaN       692
10019         47           UDG    NaN         0
...          ...           ...    ...       ...
11683          0          OTRO    NaN        11
11684          0          OTRO    NaN        60
11685          0          OTRO    NaN        37
11686          0          OTRO    NaN        10
11687          0          OTRO    NaN         5

[588 rows x 14 columns]

Total de estudiantes en carreras tecnológicas (2022-2023): 0

Histórico de estudiantes desde 2014-2015:
Empty DataFrame
Columns: [X.periodo, escuela, cve.municipio, municipio, programa, programa.desglose, clave.carr, carrera, nuevo.ingreso, egresados, titulados, clasificacion, region, matricula]
Index: []